version: '3.8'

services:
  backend:
    build:
      context: ./hackaton-starter-template
      dockerfile: Dockerfile
    container_name: springbootapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hakaton.postgres.database.azure.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: hakatonpg
      SPRING_DATASOURCE_PASSWORD: Postgres123!

  my-app-fronten:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
